---
title: "TidyTemplate"
date: 2020-09-21
output: html_output
editor_options: 
  chunk_output_type: console
---

# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache = TRUE, 
                      warning = FALSE, message = FALSE,
                      dpi = 180, fig.width = 8, fig.height = 5)

library(tidyverse)
library(tidytuesdayR)
library(scales)
theme_set(theme_light())

```

# Load the weekly Data

Download the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2018-11-20")
thanksgiving <- tt$thanksgiving_meals
```

### Cleaning

```{r}
thanksgiving <- thanksgiving %>% 
    mutate(family_income = fct_reorder(family_income, parse_number(family_income)))
```

```{r}
thanksgiving %>%
  filter(cranberry == c("Canned", "Homemade")) %>%
  group_by(family_income) %>%
  summarise(
    homemade = sum(cranberry == "Homemade"),
    total = n(),
    low = qbeta(0.025, homemade + 0.5, total - homemade + 0.5),
    high = qbeta(0.975, homemade + 0.5, total - homemade + 0.5)
  ) %>%
  ggplot(aes(family_income, homemade / total, group = 1)) +
  geom_line() +
  geom_ribbon(aes(ymin = low, ymax = high), alpha = 0.1) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "Distribution of % homemmade cranberry in various income groups",
       x = "Family Income",
       y = "% of home made carnberry")

  
```

```{r}
thanksgiving %>% 
  filter(celebrate == "Yes") %>% 
  count(family_income) %>% 
  mutate(percent = n/sum(n),
         total = sum(n),
         low = qbeta(0.025, n + 0.5, total - n + 0.5),
         high = qbeta(0.975, n + 0.5, total - n + 0.5)) %>% 
  ggplot(aes(family_income, percent, group = 1)) +
  geom_line() +
  geom_ribbon(aes(ymin = low, ymax = high), alpha = 0.1) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "% people celebration in various income groups",
       x = "Family income",
       y = "% of people celebrating Thanksgiving") 

```

```{r}
food_gathred <- thanksgiving %>% 
  select(id, starts_with(c("side","pie","dessert"))) %>%
  select(-c("side14", "side15", "pie12", "pie13", "dessert11", "dessert12")) %>% 
  pivot_longer(side1:dessert10, names_to = "type", values_to = "value") %>% 
  filter(!is.na(value),
         !value %in% c("None")) %>% 
  mutate(type = str_remove(type, "\\d+"))

food_gathred %>% 
  count(type, value, sort = T) %>% 
  ggplot(aes(fct_reorder(value,n), n, fill = type)) +
  geom_col() +
  facet_wrap(~type, scales = "free") +
  theme(legend.position = "none",) +
  coord_flip() +
  labs(title = "What are people eating?") 
```

```{r}
thanksgiving %>%
  inner_join(food_gathred) %>%
  group_by(us_region) %>%
  mutate(respondents = n_distinct(id)) %>%
  count(us_region, respondents, type, value) %>%
  ungroup() %>%
  mutate(percent = n / respondents)

```

```{r}
thanksgiving %>% 
  inner_join(food_gathred) %>% 
  filter(!is.na(prayer)) %>% 
  group_by(type, value) %>% 
  summarise(total = n(),
            prayer = sum(prayer == "Yes"),
            percent = prayer/total) %>% 
  arrange(desc(percent))
  
```

### What food goes with what?

```{r}
library(widyr)
food_gathred %>% 
  pairwise_cor(value, id, sort = T)
```

